build.gradle
src/main/java/com/example/backend/BackEndApplication.java
src/main/java/com/example/backend/controller/LoginController.java
src/main/java/com/example/backend/controller/RegisterController.java
src/main/java/com/example/backend/controller/TestController.java
src/main/java/com/example/backend/domain/BaseTime.java
src/main/java/com/example/backend/domain/EmailCheck.java
src/main/java/com/example/backend/domain/User.java
src/main/java/com/example/backend/dto/MsgEnum.java
src/main/java/com/example/backend/dto/RequestEmailCheckDto.java
src/main/java/com/example/backend/dto/RequestRegisterDto.java
src/main/java/com/example/backend/exception/ApiException.java
src/main/java/com/example/backend/repository/EmailCheckRepository.java
src/main/java/com/example/backend/repository/UserRepository.java
src/main/java/com/example/backend/security/WebSecurityConfig.java
src/main/java/com/example/backend/service/UserService.java
src/main/resources/application.properties
src/main/resources/logback-spring.xml

이메일 인증
이메일 중복확인
닉네임 중복확인
최종 회원가입
로그인시 spring-security 의존성 추가예정

#3 회원가입 기능

---

build.gradle
src/main/java/com/example/backend/controller/LoginController.java
src/main/java/com/example/backend/domain/EmailCheck.java
src/main/java/com/example/backend/domain/Role.java
src/main/java/com/example/backend/domain/User.java
src/main/java/com/example/backend/dto/MsgEnum.java
src/main/java/com/example/backend/dto/RequestLoginDto.java
src/main/java/com/example/backend/repository/EmailCheckRepository.java
src/main/java/com/example/backend/security/JwtAuthenticationFilter.java
src/main/java/com/example/backend/security/JwtTokenProvider.java
src/main/java/com/example/backend/security/UserDetailServiceImpl.java
src/main/java/com/example/backend/security/UserDetailsImpl.java
src/main/java/com/example/backend/security/WebSecurityConfig.java
src/main/java/com/example/backend/service/UserService.java

#6 이메일 로그인 기능

---

build.gradle
src/main/java/com/example/backend/board/controller/BoardController.java
src/main/java/com/example/backend/board/domain/Board.java
src/main/java/com/example/backend/board/dto/BoardRequestDto.java
src/main/java/com/example/backend/board/service/BoardService.java
src/main/java/com/example/backend/s3/AwsS3Config.java
src/main/java/com/example/backend/s3/AwsS3Service.java
src/main/java/com/example/backend/todo/dto/TodoRequestDto.java

#10 커뮤니티 게시글 작성, Todo 연관관계, S3 이미지 업로드

---

src/main/java/com/example/backend/user/security/WebMvcConfig.java
src/main/java/com/example/backend/user/security/WebSecurityConfig.java
src/main/resources/static/index.html

#11 로그인 기능 Cors 설정

---

src/main/java/com/example/backend/exception/ErrorCode.java
src/main/java/com/example/backend/s3/AwsS3Service.java
src/main/java/com/example/backend/user/controller/UserController.java
src/main/java/com/example/backend/user/domain/User.java
src/main/java/com/example/backend/user/dto/UserResponseDto.java
src/main/java/com/example/backend/user/service/UserService.java

#28 사용자 기능

---

src/main/java/com/example/backend/board/controller/BoardController.java
src/main/java/com/example/backend/board/dto/PageRequestDto.java
src/main/java/com/example/backend/exception/ErrorCode.java
src/main/java/com/example/backend/s3/AwsS3Service.java
src/main/java/com/example/backend/user/controller/UserController.java
src/main/java/com/example/backend/user/dto/PasswordRequestDto.java
src/main/java/com/example/backend/user/dto/SocialUserCheckResponseDto.java
src/main/java/com/example/backend/user/service/UserService.java

1. 비밀번호변경
2. 소셜사용자 확인
3. 이미지 저장시 https:// 프로토콜 넣기

#28 비밀번호변경, 소셜사용자 확인

---

src/main/java/com/example/backend/friend/controller/FriendRequestController.java
src/main/java/com/example/backend/friend/repository/FriendRequestRepository.java
src/main/java/com/example/backend/friend/service/FriendRequestService.java
src/main/java/com/example/backend/msg/MsgEnum.java
src/main/java/com/example/backend/todo/controller/TodoController.java
src/main/java/com/example/backend/todo/domain/Category.java
src/main/java/com/example/backend/todo/dto/TodoRequestDto.java
src/main/java/com/example/backend/todo/dto/TodoResponseDto.java
src/main/java/com/example/backend/todo/dto/TodoScopeRequestDto.java
src/main/java/com/example/backend/todo/repository/TodoRepository.java
src/main/java/com/example/backend/todo/service/TodoService.java
src/main/java/com/example/backend/user/domain/PublicScope.java
src/main/java/com/example/backend/user/domain/User.java
src/main/java/com/example/backend/user/dto/UserTodoResponseDto.java

- 공개범위 변수 추가
- 공개 범위에 따른 친구 페이지 조회 API 추가
- Todo 정렬, 페이징 수정

#35 #5 #3 회원가입 시 공개범위 ALL / 친구 페이지 조회 API / TodoRepository 수정

---

src/main/java/com/example/backend/user/config/SecurityConfig.java

#11 스웨거 포스트 요청 안되는 오류

---

src/main/java/com/example/backend/board/domain/Board.java

#10 참여자 숫자 기본값 0

---

src/main/java/com/example/backend/user/domain/User.java
src/main/java/com/example/backend/user/service/CustomOAuth2UserService.java
src/main/java/com/example/backend/user/service/UserService.java

#28 회원가입시 기본 이미지

---

src/main/java/com/example/backend/chat/controller/ChatMessageController.java
src/main/java/com/example/backend/chat/domain/ChatMessage.java
src/main/java/com/example/backend/chat/dto/response/ChatMessageResponseDto.java
src/main/java/com/example/backend/chat/service/ChatMessageService.java

채팅방 퇴장 시 메세지 추가한 내용
main 에 먼저 push 후 sub-main 에 pr 요청

메인에 먼저 푸쉬 한 내용..

---

src/main/java/com/example/backend/BackEndApplication.java
src/main/java/com/example/backend/board/domain/Board.java
src/main/java/com/example/backend/character/domain/Characters.java
src/main/java/com/example/backend/event/controller/EventController.java
src/main/java/com/example/backend/event/domain/Event.java
src/main/java/com/example/backend/event/domain/Product.java
src/main/java/com/example/backend/event/domain/Stamp.java
src/main/java/com/example/backend/event/domain/StampDate.java
src/main/java/com/example/backend/event/domain/Winning.java
src/main/java/com/example/backend/event/dto/EventRequestDto.java
src/main/java/com/example/backend/event/dto/EventResponseDto.java
src/main/java/com/example/backend/event/dto/ProductResponseDto.java
src/main/java/com/example/backend/event/repository/EventRepository.java
src/main/java/com/example/backend/event/repository/ProductRepository.java
src/main/java/com/example/backend/event/repository/StampDateRepository.java
src/main/java/com/example/backend/event/repository/StampRepository.java
src/main/java/com/example/backend/event/repository/WinningRepository.java
src/main/java/com/example/backend/event/scheduler/EventScheduler.java
src/main/java/com/example/backend/event/service/EventService.java
src/main/java/com/example/backend/exception/ErrorCode.java
src/main/java/com/example/backend/msg/MsgEnum.java
src/main/java/com/example/backend/todo/domain/Todo.java
src/main/java/com/example/backend/todo/repository/TodoRepository.java
src/main/java/com/example/backend/user/config/SecurityConfig.java
src/main/java/com/example/backend/user/domain/User.java
src/main/java/com/example/backend/user/repository/UserRepository.java
src/main/java/com/example/backend/user/service/CustomOAuth2UserService.java
src/main/java/com/example/backend/user/service/UserService.java
src/test/java/com/example/backend/event/PercentTest.java

Feature/event, 이벤트 기능 초기모델 완료

---

src/main/java/com/example/backend/chat/domain/ChatMessage.java
src/main/java/com/example/backend/chat/dto/response/ChatMessageResponseDto.java
src/main/java/com/example/backend/chat/service/ChatMessageService.java

#22 QUIT 메세지 안 나가는 오류 수정

---

src/main/java/com/example/backend/friend/service/FriendRequestService.java
src/main/java/com/example/backend/user/dto/UserTodoResponseDto.java

- 친구페이지 조회 시 캐릭터 정보 보내기
- 친구가 아닐 때 에러처리 나오는 오류 수정

#35 친구페이지 조회 수정

---

src/main/java/com/example/backend/event/scheduler/EventScheduler.java

#75 스케줄러시간 12:05분으로 조정

---

src/main/java/com/example/backend/user/dto/UserResponseDto.java
src/main/java/com/example/backend/user/service/UserService.java

메인 페이지에서 유저 정보 조회 시 오늘의 Todo 정보 추가

#39 유저 정보 조회시 오늘의 Todo 정보 포함

---

src/main/java/com/example/backend/board/controller/BoardController.java
src/main/java/com/example/backend/board/dto/response/BoardResponseDto.java
src/main/java/com/example/backend/board/service/BoardService.java

#10 참여중 flag 수정

---

src/main/java/com/example/backend/swagger/SwaggerConfig.java

#23 스웨거 refresh 부분 제거

---

src/main/java/com/example/backend/user/service/CustomOAuth2UserService.java
src/main/java/com/example/backend/user/utils/CookieUtil.java

소셜 회원 조회 Optional 처리

---

src/main/java/com/example/backend/board/domain/Board.java
src/main/java/com/example/backend/board/service/BoardService.java

#10 withTodo 취소

---

src/main/java/com/example/backend/user/controller/UserController.java
src/main/java/com/example/backend/user/service/UserService.java

#28 프로필 기본 이미지

---

src/main/java/com/example/backend/board/repository/BoardRepositoryImpl.java

#10 커뮤니티 목록 조회 정렬

---

src/main/java/com/example/backend/board/dto/response/PageBoardResponseDto.java
src/main/java/com/example/backend/board/repository/BoardRepositoryCustom.java
src/main/java/com/example/backend/board/repository/BoardRepositoryImpl.java
src/main/java/com/example/backend/board/service/BoardService.java

Slice로 변경 -> 불필요한 count query 사용 안함

#10 커뮤니티 목록 Slice로 변경

---

build.gradle
src/main/java/com/example/backend/user/utils/CookieUtil.java
src/main/resources/logback-spring.xml

slack 오류 대응
slack webhooks 기능 사용

#141 slack 오류 대응

---

src/main/java/com/example/backend/user/utils/CookieUtil.java

#6 로그인 cookie

---

src/main/java/com/example/backend/board/service/BoardService.java

저장되어있는 이미지 URL 이랑 새로 요청한 이미지 URL이랑 다를 때만 S3에서 삭제

#10 이미지 수정 시

---

src/main/resources/logback-spring.xml

#141 많은 오류 메시지 때문에 주석 처리

---

src/main/java/com/example/backend/chat/config/handler/StompHandler.java
src/main/java/com/example/backend/chat/controller/ChatMessageController.java
src/main/java/com/example/backend/chat/redis/RedisPub.java
src/main/java/com/example/backend/chat/redis/RedisSub.java
src/main/java/com/example/backend/chat/service/ChatMessageService.java

2개 저장되는 이유 : onMessage 에 도착 한 이후에 저장을 진행함.. 각 서버의 onMessage에 도착하면 각자 의 서버에서 저장을 진행해서 두개의 메세지가 저장됨. publish 하는 단계로 chatMessage 를 저장하는 위치를 변경 후 하나만 저장될듯? 아직 안해봄..

#22 채팅 2개 저장 수정

---

build.gradle
scripts/run_new_was.sh
src/main/java/com/example/backend/BackEndApplication.java
src/main/java/com/example/backend/config/SchedulerConfig.java
src/main/java/com/example/backend/event/scheduler/EventScheduler.java
src/main/java/com/example/backend/user/oauth/handler/OAuth2AuthenticationSuccessHandler.java
src/main/java/com/example/backend/user/service/UserService.java

#75 이벤트 스케줄러 동시성 Redis 이용

---

build.gradle
src/main/java/com/example/backend/msg/MsgEnum.java
src/main/java/com/example/backend/user/controller/RegisterController.java
src/main/java/com/example/backend/user/domain/EmailCheck.java
src/main/java/com/example/backend/user/service/UserService.java
src/main/resources/templates/mail.html

#3 회원가입 -> 이메일 인증 폼

---

src/main/java/com/example/backend/config/AsyncConfig.java
src/main/java/com/example/backend/mail/EmailService.java
src/main/java/com/example/backend/mail/HtmlEmailService.java
src/main/java/com/example/backend/user/controller/RegisterController.java
src/main/java/com/example/backend/user/service/UserService.java

#3 이메일 전송 속도 개선

---

src/main/resources/templates/mail.html

#28 이메일 인증 HTML 폼 변경

---

src/main/resources/templates/mail.html

#28 사용자 메일

---

README.md
src/main/java/com/example/backend/chat/controller/ChatMessageController.java
src/main/java/com/example/backend/event/service/EventService.java

메인에 먼저 푸쉬한거

---

src/main/java/com/example/backend/common/controller/CommonController.java
src/main/resources/logback-spring.xml

#141 슬랙 재설정

---

.github/workflows/gradle.yml
README.md
scripts/run_new_was.sh
src/main/java/com/example/backend/filter/TokenAuthenticationFilter.java
src/main/resources/logback-spring.xml

먼저 머지한거 ㅠㅠ

---

.github/workflows/gradle.yml
README.md
scripts/run_new_was.sh
src/main/java/com/example/backend/exception/FilterChainProxyAdvice.java
src/main/java/com/example/backend/filter/TokenAuthenticationFilter.java
src/main/resources/logback-spring.xml

슬레시 두개 올 때 예외 처리

---

src/main/java/com/example/backend/user/config/SecurityConfig.java

#9 채팅관련 CORS에러

---

src/main/java/com/example/backend/character/service/CharacterService.java
src/main/java/com/example/backend/chat/dto/request/ChatMessageRequestDto.java
src/main/java/com/example/backend/chat/service/ChatMessageService.java
src/main/java/com/example/backend/event/scheduler/EventScheduler.java
src/main/java/com/example/backend/event/service/EventService.java
src/main/java/com/example/backend/notification/controller/NotificationController.java
src/main/java/com/example/backend/notification/service/NotificationService.java
src/main/java/com/example/backend/user/config/SecurityConfig.java
src/main/java/com/example/backend/user/oauth/handler/OAuth2AuthenticationSuccessHandler.java
src/main/java/com/example/backend/user/service/UserService.java

#153 알림 기능
